services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4001:4000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - db_data:/var/lib/postgresql/data
  migrate:
    build:
      context: ./backend
      target: builder
    command: npm run migrate:up
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  seed:
    image: postgres:15
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backend/scripts/seed_base.sql:/scripts/seed_base.sql
    command: ["psql", "-h", "${DB_HOST}", "-U", "${DB_USER}", "-d", "${DB_NAME}", "-f", "/scripts/seed_base.sql"]
volumes:
  db_data: